config/routes.rb
Rails.application.routes.draw do
  get 'finder/alphabetized'

  get 'finder/missing_email'

  root to: 'finder#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
#
class Customer < ApplicationRecord
  validates :name, :email, presence: true
  belongs_to :province
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/finder_controller.rb
#
class FinderController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:name)
  end

  def missing_email
    @customers = Customer.where(email: [nil, ''])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.slim
.customer
  h1.strong = customer.name
  p = image_tag customer.image.nil? ? "" : customer.image, alt: "#{customer.name}'s picture", size: "140x180"
  - unless customer.phone.nil? || customer.phone == ''
    p 
      strong Phone: 
      = customer.phone 
  - unless customer.email.nil? || customer.email == ''
    p 
      strong Email: 
      a = customer.email 
  p 
    strong Province: 
    = (customer.email.nil? || customer.email == '') ? ' None' : customer.province
  - unless customer.notes.nil? || customer.notes == ''
    p 
      strong Notes: 
      = customer.notes  

app/views/finder/alphabetized.html.slim
h1 Alphabetized
= render partial: "layouts/nav", locals: { page: 'alphabetized' }
= render partial: 'customers/customer', collection: @customers

app/views/finder/index.html.slim
h1 All Customers
= render partial: "layouts/nav", locals: { page: 'index' }
= render partial: 'customers/customer', collection: @customers

app/views/finder/missing_email.html.slim
h1 Missing Emails
= render partial: "layouts/nav", locals: { page: 'missing_email' }
= render partial: 'customers/customer', collection: @customers

app/views/layouts/_nav.html.slim
.nav
  - unless page == 'index'
    .nav_link = link_to 'All Customers ', root_path
    .nav_link - 
  - unless page == 'alphabetized'
    .nav_link = link_to 'Alphabetized ', finder_alphabetized_path
  - if page == 'index'
    .nav_link - 
  - unless page == 'missing_email'
    .nav_link = link_to 'Missing Email', finder_missing_email_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRMChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>